# Generated by Django 6.1.1 on 2026-09-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_firebaseidentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseIdentity',
        ),
    ]
