# Generated by Django 6.1.1 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='authotp',
            name='accounts_au_email_219051_idx',
        ),
        migrations.AddIndex(
            model_name='loginotp',
            index=models.Index(fields=['email', 'created_at'], name='accounts_lo_email_eb823e_idx'),
        ),
        migrations.DeleteModel(
            name='AuthOTP',
        ),
    ]
