# Generated by Django 4.2.30 on 2026-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
