# Generated by Django 4.2.30 on 2026-09-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_skills', models.JSONField(default=list)),
                ('skills_to_improve', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('preferred_skills_missing', models.JSONField(default=list)),
                ('experience_match', models.BooleanField(default=False)),
                ('education_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='careers.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
