# Generated by Django 6.1.1 on 2026-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='optimization',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
