# Generated by Django 6.1.1 on 2026-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchresult_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='tailored_resume',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
