# Generated by Django 6.1.1 on 2026-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchresult_tailored_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='tailored_resume_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
