# Generated by Django 6.1.1 on 2026-09-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('coding', 'Coding'), ('open', 'Open Ended')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='sample_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='selected_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='session_type',
            field=models.CharField(choices=[('mcq', 'MCQ Round'), ('technical', 'Technical Round'), ('behavioral', 'Behavioral'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
    ]
