# Generated by Django 6.1.1 on 2026-09-26 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion_correct_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=180)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('question_type', models.CharField(default='conceptual', max_length=20)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.CharField(blank=True, max_length=10, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('sample_solution', models.TextField(blank=True, null=True)),
                ('model_answer', models.TextField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('ai', 'AI Generated'), ('fallback', 'Local Fallback'), ('curated', 'Curated')], default='ai', max_length=20)),
                ('question_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_question_bank_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role_id', 'skill', 'topic', 'difficulty'], name='interviews__role_id_dc4b5b_idx'), models.Index(fields=['question_type', 'difficulty'], name='interviews__questio_89e595_idx')],
            },
        ),
    ]
