# Generated by Django 6.1.1 on 2026-09-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_questionbankquestion'),
        ('roadmap', '0003_roadmapitem_completed_learning_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='roadmap_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='roadmap.roadmapitem'),
        ),
    ]
