# Generated by Django 4.2.30 on 2026-09-09 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0002_jobdescription_ai_analysis'),
        ('matching', '0001_initial'),
        ('resumes', '0002_resume_ai_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('total_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='careers.jobdescription')),
                ('match_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='matching.matchresult')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('improve', 'Improve'), ('missing', 'Missing'), ('preferred', 'Preferred')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('current_level', models.CharField(default='Not Available', max_length=50)),
                ('target_level', models.CharField(default='Intermediate', max_length=50)),
                ('reason', models.TextField()),
                ('learning_topics', models.JSONField(default=list)),
                ('practice_tasks', models.JSONField(default=list)),
                ('project_task', models.TextField(blank=True)),
                ('estimated_days', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
