# Generated by Django 6.1.1 on 2026-09-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
