# Generated by Django 6.1.1 on 2026-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmapitem_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='completed_learning_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='learning_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='learning_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='learning_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='mock_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='mock_pass_score',
            field=models.PositiveIntegerField(default=70),
        ),
    ]
