# Generated by Django 6.1.1 on 2026-09-14 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('doc', 'Documentation'), ('article', 'Article'), ('course', 'Course'), ('other', 'Other')], default='other', max_length=20)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
    ]
