# Generated by Django 6.1.1 on 2026-09-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
